{% set name = "pyscal-rdf" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscal_rdf-{{ version }}.tar.gz
  sha256: da6bae398dcea070c2b61a25843f7998ecf773983a4f8ada88fea0496cbf27c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8 
    - pip
  run:
    - python >=3.8
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - networkx
    - ipycytoscape
    - spglib
    - pyscal3 =3.1.0

test:
  imports:
    - pyscal_rdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
