{% set name = "atomrdf" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomrdf-{{ version }}.tar.gz
  sha256: 2c148a79b825e57187e0c6d67d8c2be8f6eb95f037e0ed9562f728df16b750f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - ipycytoscape
    - networkx
    - spglib
    - pyscal3 >=3.1.7
    - pandas
    - owlready2

test:
  imports:
    - atomrdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://atomrdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
